name = "VET_Unflipping"
modname = "vet_unflipping"
prefix = "vet"
author = "veteran29"
version = "1.1.0"
files = ["mod.cpp"]

keyname = "vet_unflipping_{{version}}"
signame = "{{prefix}}_{{version}}-{{git \"id 8\"}}"
reuse_private_key = true

releasebuild = [
    "!Set_version",
]

[scripts]
    [scripts.Set_version]
        steps_windows = [
            "powershell ./tools/Set-Version.ps1 {{version}}"
        ]
        # show_output = true
